version: '2'
services:
  app: &base
    build:
      context: .
    image: keboola/snowflake-transformation
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_WAREHOUSE
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_SCHEMA
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - STORAGE_API_TOKEN
      - KBC_RUNID
  dev:
    <<: *base
    volumes:
      - ./:/code
      - ./data:/data
