services:
  app: &base
    build:
      context: .
    image: keboola/snowflake-transformation
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_WAREHOUSE
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_SCHEMA
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_PRIVATEKEY
      - STORAGE_API_TOKEN
      - KBC_RUNID
      - KBC_DATA_TYPE_SUPPORT=none
    volumes:
      - ./data:/data

  dev:
    platform: linux/amd64
    <<: *base
    volumes:
      - ./:/code
      - ./data:/data
